language: node_js
node_js:
  - "14"
script:
  - npm run build
  - npm run test
deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: GNnJLPgoPLqYNl2F1wlbOIgGwZ9Lqq/aSA791M/ZnwzK77hoHcX6KjrStmvhVdAskQQMfCgM8p92k4XVJbOz9SL2LcLWkdRuRdoPzvDnDWq1fnemnsbzkyItZKLEyFwvKaQx5RGVEkzCa3rkWyJUE8RGJM8rd65R2RvO+h0srgLq8GRJsj0Hdt0zo9Ti95tJpbA2HLkNwPN+D9uZg7dV98rsNEq6yg4Ctg9KDZ3tqZpTDCM0wALIfkjys+RD1xSrjwSlWa4wkPP6sy7LlRfDIeWktRKYN/J+KY811Mi+wLk9Qx3aqhr1XgOToWYqWlCYNXKlFntVxPMJOGbQ9FF75636oqoDi724dFfuXiMMxumwChI3oHHc4Go1oT/4dTK2vOxCtnnLh+fRsoG1IX5Y020rkNIyRXGrTVWJ1sOkilgW+ooS3j9pk96arxGahDEaeoEh02mfuMZLl8WeIKtpG5X+9f1XN/aqIQxgQvZohr+8hW9TuPV6S7ZjuAaaSik7KadlJml/UwaLtAUS7FoS3KwNpz35oxBk8oOT09cnqwhmYWBxJxWzqqbC5ThFQYRjCEc4TEI6QFbQMaeDhoDrB1iOcEaoTwe9DlltYUAK01w4svkZMbbWtezF9Vb+uxEYMKb1nQYvIBMSLzug6ddrIBW1NrRrP1yLsh0rnnj+Trc=
  on:
    tags: true
    repo: dubzzz/ava-fast-check
